DROP SCHEMA IF EXISTS ZEDRAX; 

CREATE SCHEMA ZEDRAX;

USE ZEDRAX;

DROP TABLE IF EXISTS ZEDRAX.PLAYER;

CREATE TABLE ZEDRAX.PLAYER (
	ID_PLAYER INT (10) PRIMARY KEY AUTO_INCREMENT
	,SCORE INT (10) NOT NULL DEFAULT 0
);